server:
  port: 9000

---

spring:
  application:
    name: spring-boot-tutorial
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: springboot_tutorial
    url: jdbc:postgresql://localhost:5432/springboot_tutorial_db
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to SpringBoot Tutorial!!

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    username: springboot_tutorial_qa
    url: jdbc:postgresql://localhost:5432/springboot_tutorial_db_qa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to SpringBoot Tutorial!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: springboot_tutorial_prod
    url: jdbc:postgresql://localhost:5432/springboot_tutorial_db_prod
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to SpringBoot Tutorial!!